pull_request_rules:
  - name: automatic merge when CI passes patch code coverage status is good
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - status-success=codecov/patch
      - base=master
    actions:
      merge:
        method: squash
      delete_head_branch: {}