pull_request_rules:
  - name: automatic merge when CI passes and 2 reviews
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - codecov/patch
      - base=master
    actions:
      merge:
        method: squash
      delete_head_branch: {}